modLoader = "kotlinforforge" #mandatory
loaderVersion = "[4,)"
license = "MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId = "botjs"
version = "${file.jarVersion}"
displayName = "BotJS"
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="botjs.png" #optional
#credits="Thanks for this example mod goes to KOTLIN" #optional
authors = "switefaster, Yaossg, InitAuther97" #optional
description = '''
Extensible and programmable bots!
'''
[[dependencies.botjs]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.botjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
